version: '3.1'
services:
  creditsystem:
    image: credit-system-app
    build: ./
    ports:
      - "8091:8091"
    restart: always
    depends_on:
      - postges-db
    links:
      - postges-db

  postges-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=credit_system

